# Generated by Django 4.0.1 on 2023-02-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_ans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
    ]
