# Generated by Django 4.1.4 on 2023-02-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_ans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(default='Programming', max_length=500),
        ),
    ]
