# Generated by Django 4.0.1 on 2023-02-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_ans', '0003_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TimeField(default=''),
        ),
    ]
