# Generated by Django 4.1.4 on 2023-02-18 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question_ans', '0006_remove_question_id_question_que_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
