# Generated by Django 4.1.4 on 2023-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_ans', '0007_answer_date_created_answer_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='que_id',
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
