# Generated by Django 4.1.4 on 2023-02-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_ans', '0010_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
