# Generated by Django 4.0.1 on 2023-02-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_date_join', models.DateTimeField(auto_created=True)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=30)),
                ('user_password', models.CharField(max_length=20)),
                ('user_image', models.ImageField(blank=True, upload_to='Images')),
            ],
        ),
    ]
