# Generated by Django 4.1.4 on 2023-02-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('1', 'Not Selected'), ('2', 'MALE'), ('3', 'FEMALE'), ('4', 'OTHER')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='users',
            name='user_first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='user_last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
