# Generated by Django 4.0.1 on 2023-02-12 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_credentials', '0003_alter_users_user_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_date_join',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 12, 18, 4, 4, 727044)),
        ),
    ]
