# Generated by Django 4.1.4 on 2023-02-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_credentials', '0003_users_address_users_contact_no_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='about_user',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='users',
            name='profession',
            field=models.CharField(default='', max_length=200),
        ),
    ]
