# Generated by Django 4.1.4 on 2023-02-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_credentials', '0004_users_about_user_users_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_image',
            field=models.ImageField(default='Images/auser.png', upload_to='Images'),
        ),
    ]
