# Generated by Django 4.0.1 on 2023-02-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_credentials', '0005_alter_users_user_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_image',
            field=models.ImageField(default='auser.png', upload_to='Images'),
        ),
    ]
