# Generated by Django 4.0.1 on 2023-02-13 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_credentials', '0006_alter_users_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_date_join',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
